### PR TITLE
Add metadata to images and fix GoogleParser.parse function

### PR DESCRIPTION
**Pull request by OxFF00FF**
[add PIL_image_save method](https://github.com/hellock/icrawler/commit/c2cdbc9e991b2b62925ff9d67025283ba7fd61ff)
[save images with metadata](https://github.com/hellock/icrawler/commit/4282075eb7efef96898ba5ab580e569dcb343728)
[change PIL_image_save function](https://github.com/hellock/icrawler/commit/9b773343ce0ee6820977389bd340438038fd6afa)
made it so that metadata was saved in the photo, author (link to image)
description (original file name)

[change parse function](https://github.com/hellock/icrawler/commit/15905dfc8b187ed45776f42d7f2de71aa5bc53c0)
GoogleParser.parse
Now more than 1 image is downloaded and bugs are fixed

### CODE REVIEW

**Comment by ZhiyuanChen** [comment]
Hi, Thank you for your contribution! 
Would you mind to resolve the conflicts and try again?

**Comment by OxFF00FF** [comment]
solved

**Comment by ZhiyuanChen** [comment]
Unfortunately I had to undo the merge. 

I noticed you are introducing a new dependency, `piexif`. 

Can I ask what's the purpose of this new dependency?

**Comment by OxFF00FF** [comment]
it is needed in order to add EXIF ​​metadata to images. because I didn’t find another way to correctly add and read exif metadata понедельник, 29 июля 2024г., 19:06 +06:00 от Zhiyuan Chen  ***@***.*** :

**Comment by ZhiyuanChen** [comment]
> it is needed in order to add EXIF ​​metadata to images. because I didn’t find another way to correctly add and read exif metadata понедельник, 29 июля 2024г., 19:06 +06:00 от Zhiyuan Chen ***@***.*** :
> […](#)
> Unfortunately I had to undo the merge. I noticed you are introducing a new dependency, piexif. Can I ask what's the purpose of this new dependency? — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: @ github . com>

Please don't get me wrong. Adding an external dependencies is becoming more dangerous, after a series of supply chain attacks such as `xz`. 
I just want to ensure if it is absolutely necessary to add another dependency (is it necessary to add exif data?), and what are our alternative options (can we make it an optional dependency or lazy load it?) 

I trust every one is in good faith when submitting patches, but we still need to be cautious.

**Pull request merged**
