### PR TITLE
Move to newer html unescape

### LINKED ISSUE #99: BingImageCrawler AttributeError: 'HTMLParser' object has no attribute 'unescape
Please, 

I need help to resolve this error when trying to download images with BingImageCrawler.

### PR DESCRIPTION
**Pull request by kethan1**
Move to `html.unescape` from `html_parser.HTMLParser().unescape`.  `html_parser.HTMLParser().unescape` has been deprecated for a while and has been removed in 3.9. Fixes #99.

### CODE REVIEW

**Comment by kethan1** [comment]
`html.unescape` is only available in 3.4+. So it has support for all the supported Python versions and more. I am going to remove 2.7 from the CI (as it failed).

**Comment by kethan1** [comment]
Huh, the CI seems to be failing for the master branch, so I assume it's not my changes that made it fail. I might be wrong as I didn't take an extensive look at the CI.

**Comment by kethan1** [comment]
I've tested out this PR and it works reliably on 3.9. Haven't tested with other Python version, but I would assume it would work

**Comment by ZhiyuanChen** [comment]
Well, I don't think it is a good idea to remove support of Python 2.7
There are quite some options, 
1. try import http, and fallback to import html_parser.HTMLParser as http in case module not found
2. make separate package for 3.4- and 3.4+
What do you think? @hellock

**Comment by kethan1** [comment]
Python 2.7 is EOL, though I understand why it would be useful to keep support. I will add the fallback and add 2.7 and 3.4 back to the CI.

**Comment by ZhiyuanChen** [comment]
Yes I am aware Python 2 is EOL, so maybe it's better to provide separate package for python 2?

**Comment by kethan1** [comment]
It's not terribly hard to add a fallback for Python 2.7, so I think this package can still easily support 2.7.

**Comment by kethan1** [comment]
I think this package can still easily support 2.7, but I don't think it should. I don't think providing a separate package is a good idea. I think this package shouldn't support Python 2. Almost nobody uses Python 2 anymore (compared to the number of people who use Python 3). Python 2 is removed or in the process of getting removed in many major Linux OSes. Tons of other projects are dropping or have dropped support for Python 2. It somebody **really** needs to used Python 2, they can just install an older version of the package.

**Comment by ZhiyuanChen** [comment]
Thank you very much for your work. 
I have asked Kai (the owner of this repo)
It is time we deprecated support of python2.
Could you please revert the recent commit?

**Comment by kethan1** [comment]
Okay, will do!

**Comment by ZhiyuanChen** [comment]
I will merge this probably next week as I have an exam on Tuesday.
After I built the one last package that supports Python 2, which contains the fixes in https://github.com/hellock/icrawler/pull/100

**Comment by kethan1** [comment]
Okay, sure!

**Comment by ZhiyuanChen** [comment]
Sorry for the delay, just merged and published new package on PyPi

**Comment by kethan1** [comment]
All good! Thanks for merging!

**Pull request merged**
